name: Build sing-box latest release ipk files

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'sing-box version to build, format: 1.0.0'
        required: false
        default: ''

permissions:
  actions: write
  contents: write

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_generic
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget jq llvm \
            python3-pyelftools jq tree libelf-dev

      - name: Generate build keys
        run: |
          sudo apt-get update
          sudo apt-get install -y signify-openbsd
          signify-openbsd -G -n -c 'DO NOT USE - OpenWrt packages feed CI' -p packages_ci.pub -s packages_ci.sec
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "KEY_BUILD<<$EOF" >> $GITHUB_ENV
          cat packages_ci.sec >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Setup latest golang release
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Show go version
        run: |
          go version

      - name: Get latest sing-box version
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            TAG=$(curl -s 'https://api.github.com/repos/daeuniverse/dae/releases/latest' | jq -r '.tag_name' | tr -d 'v')
          else
            TAG="${{ github.event.inputs.tag }}"
          fi
          echo "sing-box latest version: $TAG"
          
          if [ -z "$TAG" ]; then
            echo "Error: Could not generate TAG."
            exit 1
          fi                
          echo "TAG=$TAG" >> $GITHUB_ENV    

          DGST_URL="https://github.com/daeuniverse/dae/releases/download/v$TAG/dae-full-src.zip.dgst"
          echo "Fetching digest from: $DGST_URL"
          
          # 2. Extract the sha256 string (1st column of the sha256 line)
          # We use -fSL to fail the script if the URL is 404
          NEW_HASH=$(curl -fSL $DGST_URL | grep 'sha256' | awk '{print $1}')
          
          if [ -z "$NEW_HASH" ]; then
            echo "Error: Could not extract SHA256 hash."
            exit 1
          fi          
          echo "SB_PKG_HASH=$NEW_HASH" >> $GITHUB_ENV
          
          
      - name: Get dae kernel config
        run: |
          git clone --depth=1 https://github.com/douglarek/build-openwrt.git kernel_config
          tree ./kernel_config
          
      - name: Build
        run: |
          git clone --depth 1 https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update packages
          cp -r feeds/packages/lang/golang /tmp/golang_backup
          
          git fetch --depth 1 origin tag v24.10.4
          git checkout v24.10.4
          cat ../kernel_config/configs/feeds.conf >> feeds.conf.default
          cat feeds.conf.default
          ./scripts/feeds update -a
          ## ./scripts/feeds install -a

          echo "Replacing Golang with backed-up version (Go 1.24+)"
          tree feeds/packages/lang/golang
          rm -rf feeds/packages/lang/golang
          tree /tmp/golang_backup
          cp -r /tmp/golang_backup/. feeds/packages/lang/golang/
          rm -rf tmp
          ./scripts/feeds update -i
          ./scripts/feeds install -a

          echo "Showing default go version after replacement"
          grep "VERSION:=" feeds/packages/lang/golang/golang/Makefile
          grep "VERSION:=" feeds/packages/lang/golang/golang-values.mk 
          
          wget https://downloads.openwrt.org/releases/24.10.4/targets/rockchip/armv8/config.buildinfo -O .config
          cat ../kernel_config/configs/kernel/*.config >> .config
          sed -i '/dahdi/d' .config
          make defconfig
          cat .config

          tree feeds/custom/net/dae

          # Convert TAG to OpenWrt-friendly format
          sed -i 's/PKG_VERSION:=.*/PKG_VERSION:=${{ env.TAG }}/g' feeds/custom/net/dae/Makefile
          sed -i 's/^PKG_HASH:=.*/PKG_HASH:=${{ env.DAE_PKG_HASH }}/g' feeds/custom/net/dae/Makefile
          cat feeds/custom/net/dae/Makefile
          
          # 1. 确保工具链和内核头文件是最新状态
          make toolchain/install
          make target/linux/compile
          
          # 2. 编译你的 dae 包
          make package/feeds/custom/dae/compile V=s

          FN=$(find ./bin -name 'dae_*.ipk' -a ! -name 'dae-geo*' | sort | head -1)
          if [ -z "$FN" ]; then
            echo "No IPK found!" && exit 2
          fi
          FN=$(basename "$FN")
          echo "PKG_NAME=$FN" >> $GITHUB_ENV

          cp bin/packages/aarch64_generic/custom/dae*.ipk $GITHUB_WORKSPACE/
          ## cd -
          ## find sdk/bin/packages -maxdepth 10

      - name: Publishing to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}
          path: |
            dae*.ipk

      - name: Read release.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat README.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT

      - name: Publishing to GitHub Releases
        continue-on-error: true
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dae*.ipk
          tag: ${{ env.TAG }}
          file_glob: true
          overwrite: true
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}
